language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag reverseproxy dng3hc/reverseproxy:v1
  - docker tag udagram-frontend:local dng3hc/udagram-frontend:v1
  - docker tag udagram-api-feed dng3hc/udagram-api-feed:v1
  - docker tag udagram-api-user dng3hc/udagram-api-user:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push dng3hc/reverseproxy:v1
  - docker push dng3hc/udagram-frontend:v1
  - docker push dng3hc/udagram-api-feed:v1
  - docker push dng3hc/udagram-api-user:v1